{
 "title": "FIO Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chainid",
    "label": "Chain ID",
    "query": {
     "query": "label_values({job=\"fio\"}, chain_id)"
    }
   },
   {
    "name": "producer",
    "query": {
     "query": "label_values({chain_id=\"$chainid\"}, producer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Producer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fio_producer_producing{chain_id=\"$chainid\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "options": {
    "content": "# &nbsp; &nbsp; ${chainid}\n         "
   }
  },
  {
   "title": "votes",
   "type": "bargauge",
   "gridPos": { "h": 30, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(fio_producer_votes{chain_id=\"$chainid\",producer=~\"$producer\"})",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  {
   "title": "Catching Up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fio_info_head_lag{chain_id=\"$chainid\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Nodeos Version / Block Height",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(fio_info_head_block{chain_id=\"$chainid\"}) by (endpoint, version)",
     "legendFormat": "{{endpoint}} {{version}}"
    }
   ]
  },
  {
   "title": "state size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "fio_db_used_bytes{chain_id=\"$chainid\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Ranking",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "fio_producer_rank{chain_id=\"$chainid\", producer=~\"$producer\"}",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  {
   "title": "peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fio_net_connected_peers{chain_id=\"$chainid\"}",
     "legendFormat": "Peers: {{endpoint}}"
    },
    {
     "expr": "fio_net_syncing_peers{chain_id=\"$chainid\"}",
     "legendFormat": "Syncing: {{endpoint}}"
    }
   ]
  }
 ]
}